export default ActionTypes = {
    SIGN_UP_USER: "SIGN_UP_USER",
    SIGN_IN_USER: "SIGN_IN_USER",
    SIGN_OUT_USER: "SIGN_OUT_USER",
    UPDATE_USER: "UPDATE_USER",
    GET_APPLIANCES: "GET_APPLIANCES",
    GET_USERS: "GET_USERS",
    TOGGLE_STATUS: "TOGGLE_STATUS"
}